Repository sourcelevel/guidelines, pull requests merged in 2019-07, with the labels that each got.

#2 Add In Development stage workflow
  resources/git_workflow.md
Labels: documentation

#3 Add commit message pratices
  README.md
  resources/commit_messages.md
  resources/pull_requests.md
Labels: enhancement

#4 Introduce Vscode Configurations to General
  resources/general.md
Labels: documentation, enhancement

#5 Add pull request template
  .github/pull_request_template.md
Labels: enhancement

#6 Add details about EOF mark
  resources/general.md
Labels: enhancement
